"use client";

import React from "react";
import { motion } from "framer-motion";
import {
  TrendingUp,
  Users,
  ShoppingCart,
  Award,
  Zap,
  ArrowRight,
  CheckCircle2,
  Sparkles,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { cn } from "@/lib/utils";
import { Navbar } from "@/components/layout/app-header";
import { Footer } from "@/components/layout/footer";

const fadeInUp = {
  initial: { opacity: 0, y: 24 as any},
  whileInView: { opacity: 1, y: 0 as any },
  viewport: { once: true, amount: 0.2 },
  transition: { duration: 0.55, ease: "easeOut" as any },
};

const PLAN_FEATURES = [
  {
    title: "Retail Profit",
    benefit: "Up to 30%",
    desc: "Earn healthy margins by selling trusted Swadeshi Ayurvedic products directly to customers in your network.",
    icon: ShoppingCart,
    color: "text-sky-600",
    bg: "bg-sky-50",
    border: "border-sky-100",
  },
  {
    title: "Direct Referral",
    benefit: "Instant 10%",
    desc: "Receive an immediate referral income every time a new Associate joins through your recommendation.",
    icon: Zap,
    color: "text-amber-600",
    bg: "bg-amber-50",
    border: "border-amber-100",
  },
  {
    title: "Team Matching",
    benefit: "Dual Bonus",
    desc: "Build balanced teams and unlock matching bonuses based on total business volume generated by both sides.",
    icon: Users,
    color: "text-emerald-600",
    bg: "bg-emerald-50",
    border: "border-emerald-100",
  },
];

const RANKS = [
  { name: "Bronze", requirement: "500 BV Matching", reward: "Star Pin" },
  { name: "Silver", requirement: "2,500 BV Matching", reward: "Mobile Fund" },
  { name: "Gold", requirement: "10,000 BV Matching", reward: "Bike Fund" },
  {
    name: "Diamond",
    requirement: "50,000 BV Matching",
    reward: "Car Fund & Luxury Trip",
  },
];

export default function BusinessPlan() {
  return (
    <>  
    <Navbar />
    <div className="min-h-screen bg-white text-slate-900">
      {/* Hero Section */}
      <section className="relative overflow-hidden bg-[#102417] pt-32 pb-24 px-6">
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute -top-10 left-1/2 h-[320px] w-[320px] -translate-x-1/2 rounded-full bg-emerald-500/20 blur-[120px]" />
          <div className="absolute bottom-0 right-0 h-[280px] w-[280px] rounded-full bg-amber-400/20 blur-[120px]" />
          <div className="absolute top-20 left-10 h-[220px] w-[220px] rounded-full bg-lime-400/10 blur-[100px]" />
        </div>

        <motion.div
          {...fadeInUp}
          className="relative z-10 mx-auto max-w-6xl text-center"
        >
          <div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-[11px] font-black uppercase tracking-[0.28em] text-[#e8a020]">
            <Sparkles size={14} />
            Financial Freedom Opportunity
          </div>

          <h1 className="mx-auto mt-8 max-w-5xl text-5xl font-black uppercase italic leading-[0.92] tracking-tight text-white md:text-7xl">
            The Hybrid{" "}
            <span className="not-italic text-[#e8a020]">Success Plan</span>
          </h1>

          <p className="mx-auto mt-6 max-w-2xl text-base leading-relaxed text-emerald-50/70 md:text-lg">
            A transparent and rewarding business model crafted for modern Indian
            entrepreneurs who want sustainable income, growth, and recognition.
          </p>

          <div className="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row">
            <Link href="/sign-up">
              <Button className="h-14 rounded-2xl bg-[#e8a020] px-10 text-xs font-black uppercase tracking-[0.2em] text-[#102417] shadow-xl hover:bg-[#d89218]">
                Start Earning Now
              </Button>
            </Link>

            <Button
              variant="outline"
              className="h-14 rounded-2xl border-white/15 bg-white/5 px-10 text-xs font-bold uppercase tracking-[0.2em] text-white hover:bg-white/10"
            >
              Download PDF Guide
            </Button>
          </div>

          <div className="mt-14 grid gap-4 rounded-[2rem] border border-white/10 bg-white/5 p-4 backdrop-blur-sm md:grid-cols-3 md:p-6">
            {[
              { label: "Retail Margin", value: "Up to 30%" },
              { label: "Referral Income", value: "Instant 10%" },
              { label: "Growth Potential", value: "Unlimited" },
            ].map((item, i) => (
              <div
                key={i}
                className="rounded-2xl border border-white/10 bg-white/5 px-5 py-5 text-left"
              >
                <p className="text-[10px] font-bold uppercase tracking-[0.25em] text-white/40">
                  {item.label}
                </p>
                <p className="mt-2 text-2xl font-black text-white">
                  {item.value}
                </p>
              </div>
            ))}
          </div>
        </motion.div>
      </section>

      {/* Income Streams */}
      <section className="px-6 py-24">
        <div className="mx-auto max-w-6xl">
          <motion.div {...fadeInUp} className="mx-auto mb-16 max-w-2xl text-center">
            <p className="text-[11px] font-black uppercase tracking-[0.3em] text-emerald-600">
              Income Streams
            </p>
            <h2 className="mt-4 text-3xl font-black uppercase tracking-tight text-slate-900 md:text-5xl">
              How You <span className="italic text-emerald-600">Make Money</span>
            </h2>
            <p className="mt-4 text-slate-500">
              Multiple earning channels designed to create predictable and scalable cash flow.
            </p>
          </motion.div>

          <div className="grid gap-8 lg:grid-cols-3">
            {PLAN_FEATURES.map((feature, i) => (
              <motion.div
                key={i}
                {...fadeInUp}
                transition={{ duration: 0.5, delay: i * 0.08 }}
                className={cn(
                  "group rounded-[2rem] border bg-white p-8 shadow-sm transition-all hover:-translate-y-1 hover:shadow-2xl",
                  feature.border
                )}
              >
                <div
                  className={cn(
                    "mb-6 flex h-14 w-14 items-center justify-center rounded-2xl",
                    feature.bg
                  )}
                >
                  <feature.icon className={cn("h-6 w-6", feature.color)} />
                </div>

                <div className="mb-4 flex items-end justify-between gap-3">
                  <h3 className="text-2xl font-black text-slate-900">
                    {feature.title}
                  </h3>
                  <span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black uppercase tracking-wide text-slate-700">
                    {feature.benefit}
                  </span>
                </div>

                <p className="mb-8 text-sm leading-relaxed text-slate-500">
                  {feature.desc}
                </p>

                <div className="space-y-3 border-t border-slate-100 pt-6">
                  {["Weekly Payouts", "No Hidden Charges", "Lifetime Validity"].map(
                    (text, idx) => (
                      <div
                        key={idx}
                        className="flex items-center gap-3 text-sm font-medium text-slate-600"
                      >
                        <CheckCircle2 className="h-4 w-4 text-emerald-500" />
                        {text}
                      </div>
                    )
                  )}
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Rank Section */}
      <section className="bg-slate-50 px-6 py-24">
        <div className="mx-auto max-w-6xl">
          <div className="overflow-hidden rounded-[2.5rem] bg-[#102417] p-8 md:p-12 lg:p-16">
            <div className="grid gap-12 lg:grid-cols-[0.95fr_1.4fr] lg:items-start">
              <motion.div {...fadeInUp}>
                <p className="text-[11px] font-black uppercase tracking-[0.3em] text-[#e8a020]">
                  Leadership Journey
                </p>
                <h2 className="mt-4 text-4xl font-black uppercase italic leading-none text-white md:text-5xl">
                  Rise Through
                  <br />
                  <span className="text-[#e8a020]">The Ranks</span>
                </h2>
                <p className="mt-6 max-w-md text-sm leading-relaxed text-emerald-50/60">
                  As your team expands, your rewards grow with it — from recognition
                  and monthly lifestyle support to premium travel and leadership perks.
                </p>

                <div className="mt-8 rounded-2xl border border-white/10 bg-white/5 p-5">
                  <div className="flex items-start gap-4">
                    <div className="rounded-xl bg-[#e8a020]/10 p-3">
                      <Award className="h-5 w-5 text-[#e8a020]" />
                    </div>
                    <div>
                      <p className="text-xs font-black uppercase tracking-[0.22em] text-white/40">
                        Special Benefit
                      </p>
                      <p className="mt-2 text-sm font-semibold text-white">
                        Leadership Pool Access starts from Gold rank
                      </p>
                    </div>
                  </div>
                </div>
              </motion.div>

              <div className="space-y-4">
                {RANKS.map((rank, i) => (
                  <motion.div
                    key={i}
                    {...fadeInUp}
                    transition={{ duration: 0.45, delay: i * 0.08 }}
                    className="group relative rounded-[1.75rem] border border-white/10 bg-white/5 p-5 transition-all hover:border-[#e8a020]/30 hover:bg-white/10"
                  >
                    <div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between">
                      <div className="flex items-center gap-4">
                        <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/10 text-sm font-black text-white">
                          {String(i + 1).padStart(2, "0")}
                        </div>
                        <div>
                          <p className="text-[10px] font-black uppercase tracking-[0.25em] text-[#e8a020]">
                            {rank.name}
                          </p>
                          <h3 className="mt-1 text-lg font-bold text-white">
                            {rank.reward}
                          </h3>
                        </div>
                      </div>

                      <div className="sm:text-right">
                        <p className="text-[10px] font-black uppercase tracking-[0.25em] text-white/30">
                          Requirement
                        </p>
                        <p className="mt-1 font-mono text-sm text-emerald-300">
                          {rank.requirement}
                        </p>
                      </div>
                    </div>
                  </motion.div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="px-6 py-24">
        <motion.div {...fadeInUp} className="mx-auto max-w-4xl text-center">
          <div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-amber-50">
            <TrendingUp className="h-10 w-10 text-[#e8a020]" />
          </div>

          <h2 className="mt-8 text-4xl font-black uppercase tracking-tight text-slate-900 md:text-6xl">
            Ready to Build Your{" "}
            <span className="italic text-emerald-600">Legacy?</span>
          </h2>

          <p className="mx-auto mt-5 max-w-2xl text-lg leading-relaxed text-slate-500">
            Join thousands of associates already building income, recognition,
            and long-term prosperity through a modern Swadeshi business ecosystem.
          </p>

          <div className="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row">
            <Link href="/sign-up">
              <Button className="h-14 rounded-2xl bg-emerald-600 px-8 text-xs font-black uppercase tracking-[0.22em] text-white hover:bg-emerald-700">
                Join Now
              </Button>
            </Link>

            <Link href="/dashboard/businessPlanCalculator">
              <Button
                variant="ghost"
                className="h-14 rounded-2xl px-6 text-xs font-black uppercase tracking-[0.22em] text-slate-700"
              >
                Try Profit Calculator <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            </Link>
          </div>
        </motion.div>
      </section>
    </div>
    <Footer />
    </>
  );
}